# TSA Working with labels
#### Extracting which of the `.aps` format image files to be analysed step by step

The TSA Passenger Screening Agorithm Kaggle competition data includes 3D image files

In [20]:
import pandas as pd

First, I want to read in the 'stage1_labels.csv' file into a Pandas dataframe (labels)

In [21]:
labels = pd.read_csv('/Users/TejasReddy9/Documents/PSA_Homeland/data/stage1_labels.csv')
labels.head()

                                        Id  Probability
0   00360f79fd6e02781457eda48f85da90_Zone1            0
1  00360f79fd6e02781457eda48f85da90_Zone10            0
2  00360f79fd6e02781457eda48f85da90_Zone11            0
3  00360f79fd6e02781457eda48f85da90_Zone12            0
4  00360f79fd6e02781457eda48f85da90_Zone13            0

As this dataset is huge (3TB size with 19,499 labels), I've started working only on Zone 6.

In [22]:
labels['Id_only'], labels['Zone'] = labels['Id'].str.split('_', 1).str
labels.head()

,Id,Probability,Id_only,Zone
0,00360f79fd6e02781457eda48f85da90_Zone1,0,00360f79fd6e02781457eda48f85da90,Zone1
1,00360f79fd6e02781457eda48f85da90_Zone10,0,00360f79fd6e02781457eda48f85da90,Zone10
2,00360f79fd6e02781457eda48f85da90_Zone11,0,00360f79fd6e02781457eda48f85da90,Zone11
3,00360f79fd6e02781457eda48f85da90_Zone12,0,00360f79fd6e02781457eda48f85da90,Zone12
4,00360f79fd6e02781457eda48f85da90_Zone13,0,00360f79fd6e02781457eda48f85da90,Zone13

Now, we can sort out entries only for Zone 6.

In [23]:
zone6 = labels[labels['Zone']=="Zone6"]
zone6.head()

,Id,Probability,Id_only,Zone
13,00360f79fd6e02781457eda48f85da90_Zone6,0,00360f79fd6e02781457eda48f85da90,Zone6
30,0043db5e8c819bffc15261b1f1ac5e42_Zone6,0,0043db5e8c819bffc15261b1f1ac5e42,Zone6
47,0050492f92e22eed3474ae3a6fc907fa_Zone6,0,0050492f92e22eed3474ae3a6fc907fa,Zone6
64,006ec59fa59dd80a64c85347eef810c7_Zone6,0,006ec59fa59dd80a64c85347eef810c7,Zone6
81,0097503ee9fa0606559c56458b281a08_Zone6,0,0097503ee9fa0606559c56458b281a08,Zone6

I want to know how many entries has Probability. For that,

In [24]:
zone6["Probability"].value_counts()

0    1031
1     116
Name: Probability, dtype: int64

Let's use sample to get some random 30 shuffled.

In [28]:
zone6.sample(30)

,Id,Probability,Id_only,Zone
16010,d390855c1cfd9c19317341a315bcc4bd_Zone6,0,d390855c1cfd9c19317341a315bcc4bd,Zone6
16384,d7bba8e9f303107db7a0feab67d8e895_Zone6,0,d7bba8e9f303107db7a0feab67d8e895,Zone6
10621,8ff23c0d13a4bc785fab433979b8621a_Zone6,0,8ff23c0d13a4bc785fab433979b8621a,Zone6
10978,954152b4213467a3fc4f95e1c3d2d6f4_Zone6,0,954152b4213467a3fc4f95e1c3d2d6f4,Zone6
2784,2872652fb050107f03868be2e3db645b_Zone6,0,2872652fb050107f03868be2e3db645b,Zone6
8887,8085d6bf5256a67fd53b545dbb53caf4_Zone6,0,8085d6bf5256a67fd53b545dbb53caf4,Zone6
2138,1e46c8904d64b835cbe5d0927579f322_Zone6,0,1e46c8904d64b835cbe5d0927579f322,Zone6
16401,d80f5b60a20b5903ed083d4307957639_Zone6,0,d80f5b60a20b5903ed083d4307957639,Zone6
4297,3f1c3df84fcc2a555d1a060ae1d24ed7_Zone6,0,3f1c3df84fcc2a555d1a060ae1d24ed7,Zone6
16112,d4e959b95db5d6f991ca7360ace49e64_Zone6,0,d4e959b95db5d6f991ca7360ace49e64,Zone6
3872,3921e192b260902666bb7dde3b550f0d_Zone6,0,3921e192b260902666bb7dde3b550f0d,Zone6
16316,d78bcc549aaa09af770f2a05fbc97e5b_Zone6,0,d78bcc549aaa09af770f2a05fbc97e5b,Zone6
5351,4c32e1b460937a1ce348abe54e23cca5_Zone6,0,4c32e1b460937a1ce348abe54e23cca5,Zone6
16231,d6e9e9b746839a8ca249f49bf3b5b101_Zone6,0,d6e9e9b746839a8ca249f49bf3b5b101,Zone6
17336,e4e72e96bffb21e55381667911281616_Zone6,0,e4e72e96bffb21e55381667911281616,Zone6
9720,87355c6d2c2b21543bbc8e9d0c3c6a87_Zone6,0,87355c6d2c2b21543bbc8e9d0c3c6a87,Zone6
727,0bda1483163734578cfe5ea429347f03_Zone6,0,0bda1483163734578cfe5ea429347f03,Zone6
12270,a43f2d8671127b363c68a954d6ed4844_Zone6,0,a43f2d8671127b363c68a954d6ed4844,Zone6
16809,df788b51010c6de82fd1a3ff755ddf31_Zone6,0,df788b51010c6de82fd1a3ff755ddf31,Zone6
6082,5891b5ec0d20533cbf0559e903773936_Zone6,0,5891b5ec0d20533cbf0559e903773936,Zone6
2070,1d6dd266503bccaae7b8ab100f6fac97_Zone6,0,1d6dd266503bccaae7b8ab100f6fac97,Zone6
6133,59081d7fe1e53727936bb79c28fdc514_Zone6,0,59081d7fe1e53727936bb79c28fdc514,Zone6
10128,8b4423eb5abdde9fb9d77166fd7641e2_Zone6,0,8b4423eb5abdde9fb9d77166fd7641e2,Zone6
16435,d8da2f1b34a2494131a45785436ad1ba_Zone6,0,d8da2f1b34a2494131a45785436ad1ba,Zone6
17727,ea6e3b358c16a95112e71f504c136dfe_Zone6,0,ea6e3b358c16a95112e71f504c136dfe,Zone6
12831,ac486c034628ee4822c99ce2e8481d6a_Zone6,0,ac486c034628ee4822c99ce2e8481d6a,Zone6
3379,31607601930f54ef5d7dcc4dd11ee822_Zone6,0,31607601930f54ef5d7dcc4dd11ee822,Zone6
982,0fc066d8ab1c5a6a42b636c1fc5876a6_Zone6,0,0fc066d8ab1c5a6a42b636c1fc5876a6,Zone6
9635,86753997b29547ca352db8a3c35b0749_Zone6,0,86753997b29547ca352db8a3c35b0749,Zone6
15058,c6949c3511a554f7ace757832886d0b4_Zone6,0,c6949c3511a554f7ace757832886d0b4,Zone6

In [30]:
zone6_sample30 = zone6.sample(30)
zone6_sample30.to_csv("zone6_sample30.csv")

These are the files that I'm going to work on. I'll download only those .aps files, then scale it to other zones. Probably extend to 3D-images.